### ISSUE TITLE
Checking virtual machine with CPU fp counters

### ISSUE THREAD

**Issue by elsamuko** [CheckPointSW/Evasions#10]
When you run `perf` on a virtual machine to count floating point operations, the result may be zero.  
Demo: https://github.com/elsamuko/perf_usage/blob/main/run.sh

Regards,
Samuel

**Comment by chkp-alexanderc** [comment]
Hi elsamuko,

We've tested the provided approach, however, it gave us very unreliable detection results, due to the fact that Linux perf tool is dependent on Linux specific code. It relies on the perf_event_open system call which is not standardized. Therefore, it cannot be utilized in our tool. 

Thanks for you contribution.
