### ISSUE TITLE
Add Linux evasion techniques ?

### ISSUE THREAD

**Issue by ShellCode33** [CheckPointSW/Evasions#5]
Great work, thanks ! :+1: 
It seems you've made a focus on Windows evasion techniques, how about doing the same for GNU/Linux VMs ?
Awesome resource if you wish to do it in the future : https://github.com/systemd/systemd/blob/master/src/basic/virt.c

**Comment by chkp-alexanderc** [comment]
Glad that you've liked it!

A lot of our techniques are Windows-specific, due to the fact, that it is currently one of the most targeted platforms by malware. We also have a number of platform-independent detections, for example, CPU features and virtualization solutions, which could be applied to Linux VMs as well.

Please note, that our evasion database is under constant development, therefore we may consider adding additional platforms\techniques in the future. Thanks for the information.
